---
- hosts: all
  gather_facts: False
  tasks:
    - debug:
        msg:
        - Access Key is {{ lookup('env', "AWS_ACCESS_KEY_ID") }}
        - Secret Key is {{ lookup('env', "AWS_SECRET_ACCESS_KEY") }}
